# Your Solution

# Deployment and Service for PostgreSQL Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "E5OJuKRE14iotwfsvHwJeqsjaKK1eKmO"
        - name: POSTGRES_DB
          value: "part2"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

# Deployment and Service for Book Catalog Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: assignment7sit722.azurecr.io/book_catalog:latest
        ports:
        - containerPort: 5051
        env:
        - name: DATABASE_URL
          value: "postgresql://dbassignment7_2_user:UchKrHNotpXwhuKVF5wHs611MDq14aVk@dpg-crcukl3v2p9s73cnbbs0-a.oregon-postgres.render.com/dbassignment7_2"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5051
  type: LoadBalancer

---
# Deployment and Service for Inventory Management Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: assignment7sit722.azurecr.io/inventory_management:latest
        ports:
        - containerPort: 5052
        env:
        - name: DATABASE_URL
          value: "postgresql://dbassignment7_2_user:UchKrHNotpXwhuKVF5wHs611MDq14aVk@dpg-crcukl3v2p9s73cnbbs0-a.oregon-postgres.render.com/dbassignment7_2"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 5052
      targetPort: 5052
  type: LoadBalancer



